replicaCount: 1

image:
  repository: ghcr.io/mine-dd/plan-eo
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: ghcr-regcred

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}