name: mine-dd
services:
  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "4000:4000"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - CHAT_API_URL=http://chat-backend:4040
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "bun install && bun run dev --host 0.0.0.0 --port 4000"
    restart: unless-stopped
    depends_on:
      - chat-backend

  chat-backend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./chat-backend:/app
    ports:
      - "4040:4040"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://ollama:11434 # #Docker-Ollama: "http://ollama:11434" # PC-Ollama: "http://host.docker.internal:11434"
    # extra_hosts: # Uncomment this for PC-Ollama instead of docker
    #   - "host.docker.internal:host-gateway"
    command: >
      sh -c "
        pip install --no-cache-dir fastapi==0.115.12 uvicorn[standard]==0.24.0 pydantic==2.11.5 python-multipart==0.0.18 langchain==0.3.25 langchain-core==0.3.58 langchain-ollama==0.3.2 langchain-experimental==0.3.4 langgraph==0.4.8 pandas==2.3.0 tabulate==0.9.0 &&
        uvicorn main:app --host 0.0.0.0 --port 4040 --reload
      "
    restart: unless-stopped
    depends_on:
      - ollama
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:4040/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama-startup.sh:/startup.sh
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/bash", "/startup.sh"]
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama_data: