name: mine-dd
services:
  # postgres:
  #   image: postgres:latest
  #   env_file:
  #     - app/.env
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
  #     POSTGRES_DB: ${DB_NAME:-plan-eo}
  #   ports:
  #     - "${DB_PORT:-5432}:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   restart: unless-stopped

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    ports:
      - "9080:8000"
    volumes:
      - ./data/cogs:/data:ro
    environment:
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - WORKERS_PER_CORE=1
      - MAX_WORKERS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 60s
      timeout: 10s
      retries: 3
    command: uvicorn titiler.application.main:app --host 0.0.0.0 --port 8000 --workers 1
    restart: unless-stopped

  # migrate:
  #   image: oven/bun:1
  #   working_dir: /app
  #   volumes:
  #     - ./app/:/app
  #   env_file:
  #     - app/.env
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=postgres
  #   command: sh -c "sleep 5 && DATABASE_URL='postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:${DB_PORT:-5432}/${DB_NAME:-topsveltekit}' bunx node-pg-migrate up"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    command: sh -c "bun install && bun run dev"
    # command: sh -c "bun install && bun run dev"
    restart: unless-stopped

  # seed:
  #   profiles:
  #     - seed
  #   image: postgres:latest
  #   env_file:
  #     - .env
  #   environment:
  #     PGPASSWORD: ${DB_PASSWORD:-postgres}
  #   command: psql -h postgres -U ${DB_USER:-postgres} -d ${DB_NAME:-plan-eo} -f /seed-database/seed.sql
  #   volumes:
  #     - ./app/seed-database:/seed-database
# volumes:
#   postgres_data:
