name: mine-dd
services:
  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "4000:4000"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - CHAT_API_URL=http://chat-backend:4040
    command: sh -c "bun install && bun run dev --host 0.0.0.0 --port 4000"
    restart: unless-stopped
    depends_on:
      - chat-backend

  chat-backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./chat-backend:/app
    ports:
      - "4040:4040"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
        pip install --no-cache-dir fastapi==0.104.1 uvicorn[standard]==0.24.0 pydantic==2.5.0 python-multipart==0.0.6 &&
        uvicorn main:app --host 0.0.0.0 --port 4040 --reload
      "
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:4040/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
