name: mine-dd
services:
  titiler:
    image: georam/titiler:latest
    platform: linux/arm64
    ports:
      - "8000:8000"
    volumes:
      - ./data/cogs:/data:ro
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.416
      - coolify.applicationId=26
      - coolify.type=application
      - coolify.name=titiler-psgw8wg4s4k4ss4k0cs80ok4-204920454795
      - coolify.resourceName=m-i-n-e-d-ddashboardmain-vckcc40kc84c8wwo4g4wokog
      - coolify.projectName=mide-dd
      - coolify.serviceName=m-i-n-e-d-ddashboardmain-vckcc40kc84c8wwo4g4wokog
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.entryPoints=http
      - traefik.http.routers.http-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.middlewares=redirect-to-https
      - "traefik.http.routers.http-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.rule=Host(`planeo.ctwhome.com`) && PathPrefix(`/`)"
      - traefik.http.routers.http-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.service=http-0-psgw8wg4s4k4ss4k0cs80ok4-titiler
      - traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.entryPoints=https
      - traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.middlewares=gzip
      - "traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.rule=Host(`planeo.ctwhome.com`) && PathPrefix(`/titiler`)"
      - traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.service=https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler
      - traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.tls=true
      - traefik.http.routers.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.middlewares=titiler-stripprefix
      - traefik.http.middlewares.titiler-stripprefix.stripprefix.prefixes=/titiler
      - traefik.http.services.http-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.loadbalancer.server.port=8000
      - traefik.http.services.https-0-psgw8wg4s4k4ss4k0cs80ok4-titiler.loadbalancer.server.port=8000
      - "caddy_0.encode=zstd gzip"
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams 8000}}"
      - "caddy_0.handle_path=/*"
      - caddy_0.header=-Server
      - "caddy_0.try_files={path} /index.html /index.php"
      - "caddy_0=https://planeo.ctwhome.com"
      - caddy_ingress_network=psgw8wg4s4k4ss4k0cs80ok4

    environment:
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - WORKERS_PER_CORE=1
      - MAX_WORKERS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 60s
      timeout: 10s
      retries: 3
    command: uvicorn titiler.application.main:app --host 0.0.0.0 --port 8000 --workers 1
    restart: unless-stopped

  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    command: sh -c "bun install && bun run dev"
    # command: sh -c "bun install && bun run dev"
    restart: unless-stopped
