name: mine-dd
services:
  titiler:
    image: georam/titiler:latest
    platform: linux/arm64
    ports:
      - "8010:8000"
    volumes:
      - ./data/cogs:/data:ro

    environment:
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif,.TIF,.tiff,.TIFF
      - GDAL_HTTP_UNSAFESSL=YES
      - VSI_CACHE_SIZE=1000000000
      - GDAL_CACHEMAX=1000
      - PYTHONWARNINGS=ignore
      - WORKERS_PER_CORE=1
      - MAX_WORKERS=1
      - CORS_ORIGINS=*
      # Uncomment and set these if you need authenticated access to R2
      # - AWS_ACCESS_KEY_ID=your_r2_access_key
      # - AWS_SECRET_ACCESS_KEY=your_r2_secret_key
      # - AWS_REGION=auto
      # - AWS_ENDPOINT_URL=https://account-id.r2.cloudflarestorage.com

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 60s
      timeout: 10s
      retries: 3
    command: uvicorn titiler.application.main:app --host 0.0.0.0 --port 8000 --workers 1
    restart: unless-stopped

  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    command: sh -c "bun install && bun run dev"
    # command: sh -c "bun install && bun run dev"
    restart: unless-stopped
