name: mine-dd
services:
  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "4000:4000"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - CHAT_API_URL=http://chat-backend:4040
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "bun install && bun run dev --host 0.0.0.0 --port 4000"
    restart: unless-stopped
    depends_on:
      - chat-backend

  chat-backend:
    build:
      context: ./chat-backend
      dockerfile: Dockerfile
    volumes:
      - ./chat-backend:/app
    ports:
      - "4040:4040"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:4040/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s