name: mine-dd
services:
  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    env_file:
      - app/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    command: sh -c "bun install && bun run dev"
    # command: sh -c "bun install && bun run dev"
    restart: unless-stopped
