# Standalone docker-compose for chat-backend development
# Use this if you want to run only the chat backend for testing

version: "3.8"

services:
  chat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app
    restart: unless-stopped
