name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./app
        run: npm install --legacy-peer-deps

      - name: Remove problematic about page
        working-directory: ./app
        run: |
          # Temporarily remove or rename the about page that's causing build issues
          if [ -f src/routes/about/+page.md ]; then
            mv src/routes/about/+page.md src/routes/about/_page.md.bak
          fi
          
          # Create a simple replacement page
          mkdir -p src/routes/about
          cat << 'EOF' > src/routes/about/+page.svelte
          <script>
            // Simple placeholder
          </script>
          
          <div class="container mx-auto p-4">
            <h1 class="text-2xl font-bold">About</h1>
            <p>This page is temporarily unavailable.</p>
          </div>
          EOF

      - name: Build
        working-directory: ./app
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          npm run build
          # create .nojekyll file to prevent GitHub from processing with Jekyll
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: "app/build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
